name: 'MCP Readiness Scanner'
description: 'Scan MCP tool definitions for production readiness issues - timeouts, retries, error handling, and more'
author: 'Nik Kale'

branding:
  icon: 'check-circle'
  color: 'green'

inputs:
  tool:
    description: 'Path to a single MCP tool definition JSON file'
    required: false
    default: ''
  tools:
    description: 'Glob pattern for multiple tool files (e.g., "tools/**/*.json")'
    required: false
    default: ''
  config:
    description: 'Path to MCP config file'
    required: false
    default: ''
  format:
    description: 'Output format: json, markdown, sarif, html'
    required: false
    default: 'markdown'
  output:
    description: 'Output file path (optional, defaults to stdout)'
    required: false
    default: ''
  min-score:
    description: 'Minimum readiness score (0-100) to pass'
    required: false
    default: '0'
  fail-on-high:
    description: 'Fail the action if high severity findings are detected'
    required: false
    default: 'false'
  fail-on-critical:
    description: 'Fail the action if critical severity findings are detected'
    required: false
    default: 'true'
  ignore-rules:
    description: 'Comma-separated list of rule IDs to ignore (e.g., "HEUR-001,HEUR-002")'
    required: false
    default: ''

outputs:
  score:
    description: 'Readiness score (0-100)'
  production-ready:
    description: 'Whether the tool is production ready (true/false)'
  findings-count:
    description: 'Total number of findings'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install mcp-readiness-scanner
      shell: bash
      run: |
        pip install git+https://github.com/nik-kale/mcp-readiness-scanner.git

    - name: Run MCP Readiness Scan
      id: scan
      shell: bash
      run: |
        set +e  # Don't exit on error, we handle it ourselves

        # Build command arguments
        SCAN_CMD=""

        if [ -n "${{ inputs.tool }}" ]; then
          SCAN_CMD="scan-tool --tool ${{ inputs.tool }}"
        elif [ -n "${{ inputs.tools }}" ]; then
          SCAN_CMD="scan-tools ${{ inputs.tools }} --glob"
        elif [ -n "${{ inputs.config }}" ]; then
          SCAN_CMD="scan-config --config-file ${{ inputs.config }}"
        else
          echo "::error::Must specify 'tool', 'tools', or 'config' input"
          exit 1
        fi

        # Add ignore rules if specified
        if [ -n "${{ inputs.ignore-rules }}" ]; then
          SCAN_CMD="$SCAN_CMD --ignore-rules ${{ inputs.ignore-rules }}"
        fi

        # Add format
        SCAN_CMD="$SCAN_CMD --format ${{ inputs.format }}"

        # Add output file if specified
        if [ -n "${{ inputs.output }}" ]; then
          SCAN_CMD="$SCAN_CMD --output ${{ inputs.output }}"
        fi

        echo "Running: mcp-readiness $SCAN_CMD"

        # Run the scan
        OUTPUT=$(mcp-readiness $SCAN_CMD 2>&1)
        EXIT_CODE=$?

        echo "$OUTPUT"

        # Set outputs (these are placeholders - actual values depend on your CLI output)
        echo "score=N/A" >> $GITHUB_OUTPUT
        echo "findings-count=N/A" >> $GITHUB_OUTPUT

        # Determine pass/fail based on exit code and settings
        if [ $EXIT_CODE -eq 2 ]; then
          echo "::warning::Critical findings detected"
          if [ "${{ inputs.fail-on-critical }}" = "true" ]; then
            echo "production-ready=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        elif [ $EXIT_CODE -eq 1 ]; then
          echo "::warning::High severity findings detected"
          if [ "${{ inputs.fail-on-high }}" = "true" ]; then
            echo "production-ready=false" >> $GITHUB_OUTPUT
            exit 1
          fi
        fi

        echo "production-ready=true" >> $GITHUB_OUTPUT
        echo "✅ MCP Readiness scan completed"
